apiVersion: v1
kind: Service
metadata:
  name: qbshop-service
  namespace: qbshop
spec:
  type: LoadBalancer
  selector:
    app: qbshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
